name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Include CI template
        uses: actions/checkout@v2
        with:
          repository: fedorl22/ci_cd_templates 
          ref: main
          path: .github/workflows/main.yml

      - name: Run CI
        run: echo "Running CI"
        

